### ISSUE TITLE
🤖 🎨 [Application setup] Add PWA capabilities & favicon to the application

### ISSUE THREAD

**Issue by jrosseel** [italanta/italanta-apps#10]
## User stories

As a user, I want to install the app on my desktop or phone for easy access.
As a user, I wish to easily retrieve the correct application tab in my browser via a favicon.

## Technical analysis

To make a web app installable, we can turn it into a PWA. Please follow the [Angular guide on PWAs](https://angular.io/guide/service-worker-getting-started) and research how this can work in an NX repository (so using the NX instead of NG CLI).

Use the images in the zip folder below for the PWA & favicon icons:

[ele-icons.zip](https://github.com/italanta/italanta-apps/files/9181375/ele-icons.zip)

**Comment by OGENDI** [comment]
Starting with this issue

**Comment by DynastyElvis** [comment]
i intend to work on this issue

**Comment by pmutua** [comment]
@lemmyMwaura you will be working on this issue

**Comment by LemmyMwaura** [comment]
> @lemmyMwaura you will be working on this issue

I'll start right away. ✅

**Comment by jrosseel** [comment]
Closed as complete
