### ISSUE TITLE
🎨 [Application design] Design of the login page

### ISSUE THREAD

**Issue by jrosseel** [italanta/italanta-apps#11]
## User stories

Login and registration are a key feature of the application. Though already possible, the design is outdated and could be better.

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical Description](#technical-description) |  [Resources](#resources)

---

### Summary

As a user, I want to login to the application so that I can use it.
As a user, I want to create an account on the application so I can start to use it.

### Description

The design looks as follows: 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/3729474/180785668-22884581-9a31-4a45-b595-cd677c621375.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/3729474/180785720-10dcee39-6fb4-4a1e-86a5-a557597cacdc.png">

### Technical description

Two tabs differentiate between the login and register functionality. The pages and components are all located in features/app/auth/login.

The code should keep the current multi-language implementation.

### Acceptance Criteria

As the authentication and authorisation flow are already decently implemented, the developer should focus on UI only. Some components will still need to be re-arranged. As much as possible, components should be re-used over duplication.

### Resources:

* Mockups: [Here goes a URL to or the name of the mockup(s) in XD];

**Comment by meshack34** [comment]
I intend to work on this
